CREATE TABLE `users` (
	`id` varchar(256) NOT NULL,
	`email` varchar(256),
	`password` varchar(256),
	`nickname` varchar(100),
	`firstName` varchar(50),
	`familyName` varchar(256),
	`referral` varchar(25),
	`role` varchar(15) NOT NULL DEFAULT 'customer',
	`level` int DEFAULT 1,
	`okto_hash` varchar(256),
	`photo_path` varchar(256),
	`wallet` varchar(256),
	`created_at` timestamp DEFAULT (now()),
	`updated_at` timestamp DEFAULT (now()),
	CONSTRAINT `users_id` PRIMARY KEY(`id`),
	CONSTRAINT `users_email_unique` UNIQUE(`email`),
	CONSTRAINT `users_referral_unique` UNIQUE(`referral`),
	CONSTRAINT `users_okto_hash_unique` UNIQUE(`okto_hash`),
	CONSTRAINT `users_wallet_unique` UNIQUE(`wallet`)
);
