services:
  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: 'qwerty'
    
# adminer:
#   image: adminer
#   restart: always
#   ports:
#     - 3005:8080
